- name: Configurar archivo queries.js desde un repositorio
  hosts: front
  become: yes
  vars_prompt:
    - name: "repo_url"
      prompt: "Introduce la URL del repositorio de GitHub (por ejemplo, https://github.com/usuario/repositorio.git)"
      private: no
    - name: "db_user"
      prompt: "Introduce el valor para user:"
      private: no
    - name: "db_host"
      prompt: "Introduce el valor para host:"
      private: no
    - name: "db_database"
      prompt: "Introduce el valor para database:"
      private: no
    - name: "db_password"
      prompt: "Introduce el valor para password:"
      private: no

  tasks:
    - name: Asegurar que git está instalado
      apt:
        name: git
        state: present

    - name: Clonar el repositorio
      git:
        repo: "{{ repo_url }}"
        dest: "~/{{ repo_url | basename | regex_replace('\\.git$', '') }}"
        clone: yes
        update: yes

    - name: Verificar si queries.js existe
      stat:
        path: "~/{{ repo_url | basename | regex_replace('\\.git$', '') }}/queries.js"
      register: queries_js

    - name: Fallar si no se encuentra queries.js
      fail:
        msg: "No se encontró el archivo queries.js en el repositorio."
      when: not queries_js.stat.exists

    - name: Reemplazar user en queries.js
      replace:
        path: "~/{{ repo_url | basename | regex_replace('\\.git$', '') }}/queries.js"
        regexp: "user: '',"
        replace: "user: '{{ db_user }}',"

    - name: Reemplazar host en queries.js
      replace:
        path: "~/{{ repo_url | basename | regex_replace('\\.git$', '') }}/queries.js"
        regexp: "host: '',"
        replace: "host: '{{ db_host }}',"

    - name: Reemplazar database en queries.js
      replace:
        path: "~/{{ repo_url | basename | regex_replace('\\.git$', '') }}/queries.js"
        regexp: "database: 'api',"
        replace: "database: '{{ db_database }}',"

    - name: Reemplazar password en queries.js
      replace:
        path: "~/{{ repo_url | basename | regex_replace('\\.git$', '') }}/queries.js"
        regexp: "password: '',"
        replace: "password: '{{ db_password }}',"

    - name: Mensaje final
      debug:
        msg: "¡Configuración completada con éxito en el archivo queries.js!"
